name: CD

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  publish:
    name: Publishing x86_64-unknown-linux-gnu
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Install Linux dependencies
        run: sudo apt-get update && sudo apt-get install -y libssl-dev libasound2-dev libdbus-1-dev libxcb-shape0-dev libxcb-xfixes0-dev

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-unknown-linux-gnu

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --locked --release --target x86_64-unknown-linux-gnu --features sixel notify

      - name: Package
        shell: bash
        run: |
          cd target/x86_64-unknown-linux-gnu/release
            tar czvf spotify_player-x86_64.tar.gz spotify_player
            shasum -a 256 spotify_player-x86_64.tar.gz > spotify_player-x86_64.sha256

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: target/x86_64-unknown-linux-gnu/release/spotify_player-*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
